### ISSUE TITLE
Add support to finishline to publish data to ELK

### ISSUE THREAD

**Issue by accorvin** [ralphbean/finishline#28]
A nice possible feature in Finishline would be to allow publishing epic/issue completion percentage metrics to an ELK instance. This would allow for creation of custom dashboards to show team progress over time.

This is something that could/should be done after the ongoing work to refactor Finishline to be more modular, allowing for adding on new functionality like this without negatively impacting other users of finishline and without making the code base unmaintainable.

**Comment by ralphbean** [comment]
Let's close this one out until we have a specific use case for it.  :p  (In the spirit of Neil's backlog discussion...)
