### ISSUE TITLE
local environment is messing output

### ISSUE THREAD

**Issue by mmaslano** [ralphbean/finishline#32]
Could you add LC_ALL="en_US.UTF-8" before each command 'shell date' (in Makefile.factory)? I had my reports partially in Czech, which is not very useful. Thanks for consideration.

**Comment by accorvin** [comment]
@mmaslano I've pulled this one into next in our internal JIRA project, so I'll get to it in the next few days.

**Comment by accorvin** [comment]
@mmaslano I've submitted a PR with this requested change. Can you take a look and confirm it fixes the issue you were seeing? https://github.com/ralphbean/finishline/pull/33
