### ISSUE TITLE
Feature: Replace content in Confluence

### ISSUE THREAD

**Issue by romanofski** [ralphbean/finishline#38]
Part of our reporting goes to Atlassian Confluence WIKI. I've written a small module which allows me to grab the generated Confluence Wiki markup, converts it to the Confluence storage representation and replace the page where our reporting takes place.

This allows me to keep a consistent reporting across all updates in Confluence in comparison to now manually replace bits.

I'll open a pull request for the new module which will allow a user to replace confluence pages with the use of the finishline Jinja templates. Happy to throw in an example too.

Would you guys be interested?

**Comment by romanofski** [comment]
@ralphbean Yes I looked at it, but since it was behind the corporate firewall and doesn't even have a license attached to it I concluded that it was no good.
I wouldn't mind having Serapis as a service pushing out a uniform status update for everyone, but at the moment that doesn't seem to be the case.

**Comment by ralphbean** [comment]
Makes sense.  Well, if you do decide to try it, ask @nirzari nicely.  She set up the jenkins job that builds our confluence pages for us and it's been humming without a hitch.

**Comment by romanofski** [comment]
Cheers, I'd be happy to if our part of management settles on a default representation of what they actually would like to see.

**Comment by accorvin** [comment]
I like this idea. One thing to note is that I'm working on some refactoring to Finishline to make it easier to configure these different output modes so that we can add new functionality scalably. I'm trying to not be too disruptive in how I'm making these changes.

**Comment by romanofski** [comment]
@accorvin @danc86 pointed me to the Google doc, so I'm aware. I do think a service like Serapis has merit for a consistent status reporting. The problem we're facing at the moment is that there is no clear picture of what detail of information people want to see in these reports. The confluence bit is basically just a low cost effort for me to get to *something*.
